README.md
frontend/package-lock.json
frontend/package.json
frontend/src/app/components/map.tsx
frontend/src/app/globals.css
frontend/src/app/page.tsx

feat(Google Maps Component): Added Google Maps Component and initial architecture
- Created .env.local so we can keep our API keys secure
- Loading in the Google Maps component onto the main homepage

Initial Google Maps Load In

---

README.md
frontend/components.json
frontend/package-lock.json
frontend/package.json
frontend/postcss.config.js
frontend/src/app/components/search.tsx
frontend/src/app/globals.css
frontend/src/app/page.tsx
frontend/src/components/ui/button.tsx
frontend/src/components/ui/input.tsx
frontend/src/lib/utils.ts
frontend/tailwind.config.js
frontend/tsconfig.json

- Downloaded and set up ShadCN & Tailwind for development use.
- Created first component, search bar for Map
- Changed README to be better able to read.

feat(Search UI): Added ShadCN & Search Bar

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/components/activitySelector.tsx
frontend/src/app/components/homebase.tsx
frontend/src/app/components/navbar.tsx
frontend/src/app/components/search.tsx
frontend/src/app/globals.css
frontend/src/app/page.module.css
frontend/src/app/page.tsx
frontend/src/components/ui/accordion.tsx
frontend/tailwind.config.ts
frontend/tsconfig.json

- Created inital UI using CSS Flexbox and layout
- Created individual components for all UI aspects

feat(UI) Created flexible UI and components for Homebase initial UI and Layout.

---

frontend/src/app/components/homebase.tsx
frontend/src/app/components/homebaseModal.tsx
frontend/src/app/globals.css

Features:
- Is available when first loading webpage if a location is not specified in local storage
- Location is able to be changed and saved.

feat(UI): Added a modal for inputing the HomeBase address

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/components/activitySelector.tsx
frontend/src/app/components/homebase.tsx
frontend/src/app/globals.css
frontend/src/app/page.tsx
frontend/src/components/ui/dialog.tsx
frontend/src/components/ui/dropdown-menu.tsx
frontend/src/components/ui/select.tsx

Features: 
- Dialog Modal that pops up when  + button beside activity groups is hit.  
- Custom Activity groups with a dropdown menu that when clicked gives the option to add to or remove.

feat(Activity selector UI): Created Custom Activity Selector UI

---

backend/info_manager_dict.py
backend/main.py

Created the dictionary for storing information. Homebase location stored as a latitude and longitude, which is what the nearby search api call needs. Stores Place objects which. have the coordinates as well as the name and location ID. Place data structure subject to change as needed.

Info manager

---

.gitignore
backend/info_manager_dict.py
backend/main.py

Fleshed out the homebase api call and added statements for importing the gmaps object for making api calls. Added a .env file for storing the api key (included in the .gitignore file).

Homebase API call

---

frontend/src/app/components/map.tsx
frontend/src/app/components/search.tsx
frontend/src/app/components/useGoogleMapsLoader.tsx
frontend/src/app/page.tsx

- Enabled the Places API for autocomplete for the search fields
- Moved the functionality to load the map  and API to a higher  level by making a custom hook for it

feat(UI): Search Bar Autocomplete Functionality

---

frontend/src/app/components/activitySelector.tsx
frontend/src/app/components/data.ts
frontend/src/app/components/homebase.tsx
frontend/src/app/components/homebaseModal.tsx
frontend/src/app/components/map.tsx
frontend/src/app/components/search.tsx
frontend/src/app/globals.css
frontend/src/app/page.tsx

This is a bit of a bulky PR ladies and gentlemen so buckle up
- Added Custom Markers onto the map, these are populated by fake data in data.ts
- Added functionality so when you search for a place in the searchbar or homebase it actually goes and to that location and when you click on the pin it gives you the option to add the location to an activity group.
- Created Functionality and fake data for the Activity selector so when you click on it it shows a dropdown of all the activities inside.  In reality its not going to look like that, its a rough initial draft that needs a lot of work. 
- Added search functionality to the Homebase Modal.

feat(UI): Added Custom Markers & Full Functionality for Activity Selectors

---

frontend/src/app/components/activitySelector.tsx
frontend/src/app/components/map.tsx
frontend/src/app/page.tsx
frontend/src/lib/utils.ts

- Refactored Code to work with activity group and places classes. 
- Added Functionality to add from search to activity groups 
-

feat(UI): Activity Selector Functionality

---

.gitignore
backend/info_manager_dict.py
backend/main.py

Add /place/add and /place/get API endpoints

---

frontend/package-lock.json
frontend/src/app/components/activitySelector.tsx
frontend/src/app/components/map.tsx
frontend/src/app/components/search.tsx
frontend/src/app/globals.css

- added information on the marker once clicked now displayed address and name 
- added information for the activity in the activity group now displayed address and name 
- added UI functionality to remove activities from an activity group
- added UI functionality so you can add and remove new activities

Activity info display and functionality

---

frontend/src/app/components/homebase.tsx
frontend/src/app/components/homebaseModal.tsx
frontend/src/app/components/map.tsx
frontend/src/app/page.tsx

- Homebase will display always on the map
- When loaded, if there is a homebase saved the map will switch to that position. 
-

feat(UI): Added Homebase Map Functionality

---

backend/info_manager_dict.py
backend/main.py
backend/tests/test_info_manager_dict.py

Updated the backend to include /activity-group api calls and updated the info_manager to handle activity group-wise storage.
Also updated tests to reflect new functionality.

Activity Group API Endpoints

---

frontend/src/app/components/activitySelector.tsx
frontend/src/app/components/map.tsx
frontend/src/app/page.tsx

Added it so when you click on an activity group it places the markers on the map.
NOTE: I still need to do so when you click on an item in the activity group it focuses the map there and it does not currently displace the labels correctly if clicked on but I will fix all of that in the next update.

feat(UI): Activity group markers

---

backend/info_manager_dict.py
frontend/src/app/components/activitySelector.tsx
frontend/src/app/page.tsx

Remove hard coded activity groups and add /activity-group API call

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/components/dailyActivities.tsx
frontend/src/app/components/routeOptimization.tsx
frontend/src/app/globals.css
frontend/src/app/page.tsx
frontend/src/components/ui/button.tsx
frontend/src/components/ui/calendar.tsx
frontend/src/components/ui/pagination.tsx

Changed the UI and based it all around dates instead.

feat(Daily plan UI): Added days based on dates as well as changed UI 

---

frontend/src/app/components/activitySelector.tsx
frontend/src/app/components/dailyActivities.tsx
frontend/src/app/components/homebase.tsx
frontend/src/app/components/map.tsx
frontend/src/app/components/navbar.tsx
frontend/src/app/components/search.tsx
frontend/src/app/globals.css
frontend/src/app/page.tsx

Changed some colors and UI so it looks good now lol.

Added a new light background

---

frontend/src/app/components/activitySelector.tsx
frontend/src/app/components/map.tsx
frontend/src/app/globals.css
frontend/src/app/page.tsx

-  You can now have and display multiple activity groups open on the map at the same time
- Changed some stuff with the code so you can edit and save activity group colors.

Added functionality to include having multiple activitygroups open

---

frontend/src/app/components/dailyActivities.tsx

updated the daily plan format and visuals

Updated the css and formatting for daily plan section
